### ISSUE TITLE
デッキにて正常にOGPが展開されない

### ISSUE THREAD

**Issue by kazu0617** [neos-love/misskey#15]
## 💡 Summary

デッキにて正常にOGPが展開されない
io、他のインスタンスでは表示される

## 🥰 Expected Behavior

OGPの展開が正常に行われる

## 🤬 Actual Behavior

OGPの展開が正常に行われない

## 📝 Steps to Reproduce

1. デッキ表示に変更
2. URLがついている投稿を確認し、OGP展開されていないことを確認
3. 別インスタンスで同じ投稿を確認し、OGP展開されていることを確認

misskey.neos.love から確認した様子
![image](https://user-images.githubusercontent.com/6259214/216936592-eaba4967-eab5-401d-8444-33f5cd3be4fc.png)

他インスタンス(misskey.io / misskey.m544.net)から確認した様子
![image](https://user-images.githubusercontent.com/6259214/216936639-77e8c709-8b01-4c6d-b9ec-6b91058f4535.png)
![image](https://user-images.githubusercontent.com/6259214/216936752-2ffc359e-09f9-48d0-ba5c-8a8dfe0d8e4c.png)

## 📌 Environment

Misskey version: 最新(2023/02/06時点)
Your OS: Windows
Your browser: Edge / Firefox

**Comment by rassi0429** [comment]
なおした
